export const SEND_ENQUIRY = 'SEND_ENQUIRY';
export type SEND_ENQUIRY = typeof SEND_ENQUIRY;

export const SEND_ENQUIRY_SUCCESS = 'SEND_ENQUIRY_SUCCESS';
export type SEND_ENQUIRY_SUCCESS = typeof SEND_ENQUIRY_SUCCESS;

export const SEND_ENQUIRY_ERROR = 'SEND_ENQUIRY_ERROR';
export type SEND_ENQUIRY_ERROR = typeof SEND_ENQUIRY_ERROR;